version: '3'
services:
  app:
    image: your-app-image
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "80:80"
    networks:
      - prod-net
networks:
  prod-net:
    driver: overlay
