version: '3'
services:
  app:
    image: your-app-image
    deploy:
      replicas: 2
    ports:
      - "8081:80"
    networks:
      - staging-net
networks:
  staging-net:
    driver: overlay
